---
extends: airbnb
plugins:
  - import
  - jest
parserOptions:
  ecmaVersion: 2017
  sourceType: module
env:
  node: true
  browser: true
rules:
  jest/no-focused-tests: 2
  jest/no-identical-title: 2
